language: nim
sudo: required
services:
  - docker
env:
  matrix:
      IMG=yglukhov/nim-base
      IMG=nimlang/nim
before_install:
  - docker pull "$IMG"
script:
  - docker run -v "$(pwd):/project" -w /project "$IMG" nim --version
  - docker run -v "$(pwd):/project" -w /project "$IMG" nimble install
